// playgrounds/angular/src/app/examples/pager-example/pager-example.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-pager-example',
  templateUrl: './pager-example.component.html',
  styleUrls: ['./pager-example.component.scss']
})
export class PagerExampleComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="example">
  <div class="example__title">Pager example</div>
  <div class="example__control">
    <dx-pager
      [selectedPage]="1"
      [selectedPageSize]="20"
      [pageCount]="20"
      [pageSizes]="[10, 20, 30]">
      >
    </dx-pager>
  </div>
</div>

// playgrounds/react/src/examples/pagerExample.tsx
import React from 'react';
import {DxPager} from '@dx/react/components/pager';
import '@dx/react/pager.css';


function PagerExample() {
  return <React.Fragment>
    <div className="example">
      <div className="example__title">
        Pager example
      </div>
      <div className="example__control">
        <DxPager pageCount={20}
                 selectedPage={1}
                 pageSizes={[10, 20, 30]}
                 selectedPageSize={20}
        />
      </div>
    </div>
  </React.Fragment>
}

export {
  PagerExample,
}
