// playgrounds/angular/src/app/examples/simple-button-example/simple-button-example.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-simple-button-example',
  templateUrl: './simple-button-example.component.html',
  styleUrls: ['./simple-button-example.component.scss']
})
export class SimpleButtonExampleComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="example">
  <div class="example__title">Simple button example</div>
  <div class="example__control">
    <dx-simple-button [text]="'Hello!'">
    </dx-simple-button>
  </div>
</div>

// playgrounds/react/src/examples/simpleButtonExample.tsx
import React from 'react';
import {DxSimpleButton} from '@dx/react/components/simpleButton';
import '@dx/react/simpleButton.css';


function SimpleButtonExample() {
  return <React.Fragment>
    <div className="example">
      <div className="example__title">
        Simple button example
      </div>
      <div className="example__control">
        <DxSimpleButton text="hello!"/>
      </div>
    </div>
  </React.Fragment>
}

export {
  SimpleButtonExample,
}
