// libs/react/src/components/slideToggle/containers/dxSlideToggleTextContainer.tsx
import React, {useEffect, useState} from "react";
import {
  getSlideToggleTextVM,
  ISlideToggleTextVM,
  SlideToggleStore
} from "@dx/core/components/slideToggle";

import {DxSlideToggleTextView} from "../views/dxSlideToggleTextView";
import {DxSlideToggleContext} from "../dxSlideToggleContext";
import {useReactContext} from "../../../utils";


function DxSlideToggleTextContainer() {
  const store = useReactContext<SlideToggleStore>(DxSlideToggleContext);
  const [viewModel, setViewModel] = useState<ISlideToggleTextVM>();

  // init
  useEffect(() => {
    const subscription = store.getViewModel(
      (state) => state.viewData.text,
      getSlideToggleTextVM,
    ).subscribe(setViewModel);

    // destroy
    return () => {
      subscription.unsubscribe();
    }
  }, []);

  return <DxSlideToggleTextView viewModel={viewModel} />
}

export {DxSlideToggleTextContainer}

// libs/angular-workspace/projects/angular-lib/components/slide-toggle/containers/dx-slide-toggle-text-container/dx-slide-toggle-text-container.component.ts
import {ChangeDetectionStrategy, Component} from '@angular/core';
import {
  getSlideToggleTextVM,
  ISlideToggleTextVM,
  SlideToggleStore
} from "@dx/core/components/slideToggle";
import {Observable} from "rxjs";

@Component({
  selector: 'dx-slide-toggle-text-container',
  templateUrl: './dx-slide-toggle-text-container.component.html',
  styleUrls: ['./dx-slide-toggle-text-container.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DxSlideToggleTextContainerComponent {

  viewModel$: Observable<ISlideToggleTextVM> = this.store.getViewModel(
    (state) => state.viewData.text,
    getSlideToggleTextVM,
  );

  constructor(private store: SlideToggleStore) {
  }
}

<dx-slide-toggle-text-view *ngIf="viewModel$ | async as viewModel" [viewModel]="viewModel"></dx-slide-toggle-text-view>
