// libs/angular-workspace/projects/angular-lib/components/pager/containers/dx-pager-container.component.ts
import {ChangeDetectionStrategy, Component, Inject, OnInit} from '@angular/core';
import {useViewModel} from '@dx/angular-common';
import {
  ContainerPagerCore, PageNumberVM, PageSizeVM, RootTemplateVM, SelectPageAction, SelectPageSizeAction,
} from '@dx/core/components/pager';
import {combineLatest, map, Observable} from 'rxjs';
import {PAGER_CONTEXT_TOKEN, PagerContext} from '../context';
import {PageNumberAngularVM, PageSizeAngularVM, RootTemplateAngularVM} from '../types';
import {DxPagerViewBase, DxPagerViewData,} from '../views';


@Component({
  selector: 'dx-pager-container',
  template: `
    <dx-dynamic-template *ngIf="template$ && viewModel$"
                         [template]="template$ | async"
                         [data]="viewModel$ | async">
    </dx-dynamic-template>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DxPagerContainerComponent implements OnInit {
  viewModel$?: Observable<DxPagerViewData>;
  template$?: Observable<DxPagerViewBase>;

  private core?: ContainerPagerCore;

  constructor(@Inject(PAGER_CONTEXT_TOKEN) private contextContainer: PagerContext) {
  }

  ngOnInit(): void {
    this.core = this.contextContainer.context!;

    this.template$ = useViewModel<RootTemplateVM, RootTemplateAngularVM>(this.core.viewModels.rootTemplate)
      .pipe(map(({template}) => template));

    this.viewModel$ = combineLatest([
      useViewModel<PageNumberVM, PageNumberAngularVM>(this.core.viewModels.pageNumber),
      useViewModel<PageSizeVM, PageSizeAngularVM>(this.core.viewModels.pageSize),
    ]).pipe(
      map(([pageNumberVM, pageSizeVM]) => ({
        viewModel: {
          pageNumberViewModel: pageNumberVM,
          pageSizeViewModel: pageSizeVM,
        },
        actions: {
          selectPage: (value: number) => this.core?.dispatch(new SelectPageAction(value)),
          selectPageSize: (value: number) => this.core?.dispatch(new SelectPageSizeAction(value))
        }
      }))
    );
  }
}

// libs/react/src/components/pager/containers/dxPagerContainer.tsx
import React, {useContext, useMemo} from 'react';
import {
  SelectPageAction,
  SelectPageSizeAction,
  PageNumberVM,
  PageSizeVM,
  RootTemplateVM,
} from '@dx/core/components/pager';
import {useViewModel} from '../../../internal';
import { PagerContext } from '../dxPagerContext';
import {PageNumberReactVM, PageSizeReactVM, RootTemplateReactVM} from '../types';

//* Component={"name":"DxPagerContainer"}
// TODO inferno isn't support React.memo(
export function DxPagerContainer() {
  const core = useContext(PagerContext)!;
  const pageNumberViewModel = useViewModel<PageNumberVM, PageNumberReactVM>(core.viewModels.pageNumber);
  const pageSizeViewModel = useViewModel<PageSizeVM, PageSizeReactVM>(core.viewModels.pageSize);
  const rootTemplate = useViewModel<RootTemplateVM, RootTemplateReactVM>(core.viewModels.rootTemplate);

  const selectedPageChange = useMemo(() => (pageNumber: number) => {
    core.dispatch(new SelectPageAction(pageNumber))
  }, []);
  const selectedPageSizeChange = useMemo(() => (pageSize: number) => {
    core.dispatch(new SelectPageSizeAction(pageSize))
  }, []);


  const { template } = rootTemplate;
  const templateData = {
    data: {
      pageNumberViewModel,
      pageSizeViewModel,
      selectedPageChange,
      selectedPageSizeChange
    }
  };

  return (
    template(templateData)
  )
}
//);
