// libs/react/src/components/slideToggle/views/dxSlideToggleIndicatorView.tsx
import React from "react";
import {ISlideToggleIndicatorVM} from "@dx/core/components/slideToggle";


import "./dxSlideToggleIndicatorView.scss";

interface IDxSLideToggleIndicatorViewProps {
  viewModel: ISlideToggleIndicatorVM,
}

const DEFAULT_DX_SLIDE_TOGGLE_INDICATOR_PROPS: IDxSLideToggleIndicatorViewProps = {
  viewModel: {
    value: false,
    textPosition: 'right'
  }
}

function DxSlideToggleIndicatorView({viewModel}: {viewModel: ISlideToggleIndicatorVM}) {
  return (
    <div className={`dx-slide-toggle-indicator ${viewModel.textPosition === 'right' ? '-left' : '-right'}`}>
      <div className={`dx-slide-toggle-line ${!viewModel.value ? '-off' : '-on'}`}>
        <div className={`dx-slide-toggle-thumb ${!viewModel.value ? '-off' : '-on'}`}>
        </div>
      </div>
    </div>
  )
}

DxSlideToggleIndicatorView.defaultProps = DEFAULT_DX_SLIDE_TOGGLE_INDICATOR_PROPS;

export {DxSlideToggleIndicatorView}

// libs/angular-workspace/projects/angular-lib/components/slide-toggle/views/dx-slide-toggle-indicator-view.component.ts
import {ChangeDetectionStrategy, Component} from '@angular/core';
import {DxViewModelContracts} from '@dx/angular-common';
import {ISlideToggleState} from '@dx/core/components/slideToggle';

@Component({
  template: '',
})
export abstract class DxSlideToggleIndicatorViewContracts
  extends DxViewModelContracts<ISlideToggleState> {
}

@Component({
  selector: 'dx-slide-toggle-indicator-view',
  template: `
    <div class="dx-slide-toggle-indicator"
         [class.-left]="viewModel.config.textPosition === 'right'"
         [class.-right]="viewModel.config.textPosition === 'left'">
      <div class="dx-slide-toggle-line"
           [class.-off]="!viewModel.value"
           [class.-on]="viewModel.value">
        <div class="dx-slide-toggle-thumb"
             [class.-off]="!viewModel.value"
             [class.-on]="viewModel.value">
        </div>
      </div>
    </div>
  `,
  styleUrls: ['./dx-slide-toggle-indicator-view.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DxSlideToggleIndicatorViewComponent extends DxSlideToggleIndicatorViewContracts {
}
