// libs/react/src/components/pager/dxPager.tsx
import React, {useCallback, useEffect, useMemo} from 'react';
import {DxPagerLogic, PagerState, DxPagerOutputs} from '@dx/core/components/pager';
import {useOutput, useViewModel} from '../../common/hooks';
import {IDxPagerProps} from './dxPagerProps';

import './dxPager.scss';

function DxPager(props: IDxPagerProps) {
  const state = useMemo(() => new PagerState(), []);
  const logic = useMemo(() => new DxPagerLogic(state), []);
  const outputs = useMemo(() => new DxPagerOutputs(state), []);

  const pageSizeVM = useViewModel(logic.pageSizeVM$);
  const pageNumberVM = useViewModel(logic.pageNumberVM$);


  useEffect(() => logic.updateStateFromPropsAction(props), [props]);
  useOutput(outputs.outputs$.selectedPageChange, props.selectedPageChange);
  useOutput(outputs.outputs$.selectedPageSizeChange, props.selectedPageSizeChange);

  const selectPage = useCallback((selectedPage: number) => () => logic.selectPageAction(selectedPage), []);
  const selectPageSize = useCallback((selectedPageSize: number) => () => logic.selectPageSizeAction(selectedPageSize), []);

  return (
    <div className="dx-pager">
      <div className="dx-pager-page-size">
        {
          pageSizeVM && pageSizeVM.items.map((pageSizeItem) => {
            return <div key={pageSizeItem.value}
                        className={`dx-pager-page-size__item ${pageSizeItem.selected ? '-selected' : ''}`}
                        onClick={selectPageSize(pageSizeItem.value)}>
              {pageSizeItem.label}
            </div>
          })
        }
      </div>
      <div className="dx-pager-pages">
        {
          pageNumberVM && pageNumberVM.items.map((pageItem) => {
            return <div key={pageItem.value}
                        className={`dx-pager-pages__item 
                        ${pageItem.selectable ? '-selectable' : ''}
                        ${pageItem.selected ? '-selected' : ''}`}
                        onClick={selectPage(pageItem.value)}>
              {pageItem.label}
            </div>
          })
        }
      </div>
    </div>
  )
}

export {
  IDxPagerProps,
  DxPager,
}

// libs/angular-workspace/projects/angular-lib/components/pager/dx-pager.component.ts
import {ChangeDetectionStrategy, ChangeDetectorRef, Component, forwardRef, OnChanges, OnInit} from '@angular/core';
import {DxPagerLogic, DxPagerOutputs, PagerState} from '@dx/core/components/pager';
import {IPagerState} from '@dx/core/types/pager';
import {map, Subject, takeUntil} from 'rxjs';
import {DxPagerContracts} from '@dx/angular-common';

@Component({
  selector: 'dx-pager',
  templateUrl: './dx-pager.component.html',
  styleUrls: ['./dx-pager.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    {provide: DxPagerContracts, useExisting: forwardRef(() => DxPagerComponent)},
    {provide: PagerState, useClass: PagerState},
    {
      provide: DxPagerLogic,
      useFactory: (state: PagerState) => new DxPagerLogic(state),
      deps: [PagerState],
    },
    {
      provide: DxPagerOutputs,
      useFactory: (state: PagerState) => new DxPagerOutputs(state),
      deps: [PagerState],
    },
  ]
})
export class DxPagerComponent extends DxPagerContracts implements
    OnInit,
    OnChanges {

  pageSizeVM$ = this.logic.pageSizeVM$.pipe(map(({items}) => items));
  pageNumberVM$ = this.logic.pageNumberVM$.pipe(map(({items}) => items));

  private destroy$ = new Subject<void>();

  constructor(private logic: DxPagerLogic,
              private outputs: DxPagerOutputs,
              private cdr: ChangeDetectorRef) {
    super();
  }

  ngOnInit(): void {
    this.outputs.outputs$.selectedPageChange
      .pipe(takeUntil(this.destroy$))
      .subscribe((value: number) => this.selectedPageChange.emit(value));

    this.outputs.outputs$.selectedPageSizeChange
      .pipe(takeUntil(this.destroy$))
      .subscribe((value: number) => this.selectedPageSizeChange.emit(value));
  }

  ngOnChanges(): void {
    this.logic.updateStateFromPropsAction(this);
  }

  selectPage(selectedPage: number): void {
    this.logic.selectPageAction(selectedPage);
  }

  selectPageSize(selectedPageSize: number): void {
    this.logic.selectPageSizeAction(selectedPageSize);
  }

  override updateInputs(props: Partial<IPagerState>): void {
    this.logic.updateStateFromPropsAction({
      selectedPage: props.selectedPage,
      selectedPageSize: props.selectedPageSize,
      pageCount: props.pageCount,
      pageSizes: props.pageSizes,
    });
  }

  trackByRecordId({recordId}: {recordId: string}): string {
    return recordId;
  }
}

<ng-container *ngIf="pageNumberVM$ | async as pageNumberVM">
  <ng-container *ngIf="pageSizeVM$ | async as pageSizeVM">
    <div class="dx-pager">
      <!-- page size -->
      <div class="dx-pager-page-size">
        <div *ngFor="let item of pageSizeVM"
             class="dx-pager-page-size__item"
             [class.-selected]="item.selected"
             (click)="selectPageSize(item.value)">
          {{ item.label }}
        </div>
      </div>

      <!-- page number -->
      <div class="dx-pager-pages">
        <div *ngFor="let item of pageNumberVM"
             class="dx-pager-pages__item"
             [class.-selected]="item.selected"
             [class.-selectable]="item.selectable"
             (click)="selectPage(item.value)">
          {{ item.label }}
        </div>
      </div>
    </div>
  </ng-container>
</ng-container>
