// libs/angular-workspace/projects/angular-lib/components/pager/views/dx-pager-page-size-item-view.component.ts
import {ChangeDetectionStrategy, Component} from '@angular/core';
import {DxViewBase} from '@dx/angular-common';
import {ItemAngularVM} from '../types';


interface DxPagerPageSizeItemActions {
  selectPageSize: (pageSize: number) => void;
}

@Component({
  template: '',
})
export abstract class DxPagerPageSizeItemViewBase
  extends DxViewBase<ItemAngularVM<DxPagerPageSizeItemViewComponent>, DxPagerPageSizeItemActions> {
}

@Component({
  selector: 'dx-pager-page-size-item-view',
  template: `
    <div class="dx-pager-page-size__item"
         [class.-selected]="viewModel.selected"
         (click)="actions.selectPageSize(viewModel.value)">
      {{ viewModel.label }}
    </div>
  `,
  styleUrls: ['./dx-pager-page-size-item-view.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DxPagerPageSizeItemViewComponent extends DxPagerPageSizeItemViewBase {
}

// libs/react/src/components/pager/views/dxPagerPageSizeItemView.tsx
import React from 'react';
import {IPagerPageSizeItemReact} from '../types';

interface IDxPagerPageSizeItemViewProps {
  item: IPagerPageSizeItemReact;
  selectPageSize: (pageSize: number) => () => void;
}

function DxPagerPageSizeItemView({item, selectPageSize}: IDxPagerPageSizeItemViewProps) {
  return (
    <div key={item.value}
         className={`dx-pager-page-size__item ${item.selected ? '-selected' : ''}`}
         onClick={selectPageSize(item.value)}>
      {item.label}
    </div>
  )
}

export type {IDxPagerPageSizeItemViewProps};
export {DxPagerPageSizeItemView};
