// libs/react/src/components/pager/views/dxPagerPageNumberItemView.tsx
import React from 'react';
import {IPagerPageNumberItemReact} from '../types';

interface IDxPagerPageNumberItemViewProps {
  item: IPagerPageNumberItemReact;
  selectPage: (pageNumber: number) => () => void;
}

function DxPagerPageNumberItemView({item, selectPage}: IDxPagerPageNumberItemViewProps) {
  return (
    <div key={item.value}
         className={`dx-pager-pages__item 
                        ${item.selectable ? '-selectable' : ''}
                        ${item.selected ? '-selected' : ''}`}
         onClick={selectPage(item.value)}>
      {item.label}
    </div>
  )
}

export type {IDxPagerPageNumberItemViewProps};
export {DxPagerPageNumberItemView};

// libs/angular-workspace/projects/angular-lib/components/pager/views/dx-pager-page-number-item-view.component.ts
import {ChangeDetectionStrategy, Component} from '@angular/core';
import {DxViewContracts} from '@dx/angular-common';
import {ItemAngularVM} from '../types';

interface DxPagerPageNumberItemActions {
  selectPage: (pageNumber: number) => void;
}

@Component({template: ''})
export abstract class DxPagerPageNumberItemViewContracts
  extends DxViewContracts<ItemAngularVM<DxPagerPageNumberItemViewComponent>, DxPagerPageNumberItemActions> {
}

@Component({
  selector: 'dx-pager-page-number-item-view',
  template: `
    <div class="dx-pager-pages__item"
         [class.-selected]="viewModel.selected"
         [class.-selectable]="viewModel.selectable"
         (click)="actions.selectPage(viewModel.value)">
      {{ viewModel.label }}
    </div>
  `,
  styleUrls: ['./dx-pager-page-number-item-view.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DxPagerPageNumberItemViewComponent extends DxPagerPageNumberItemViewContracts {
}
