// libs/react/src/components/pager/views/dxPagerPageSizeView.tsx
import React from 'react';
import {IPagerPageSizeReactVM} from '../types';

interface IDxPagerPageSizeViewProps {
  viewModel: IPagerPageSizeReactVM;
  selectPageSize: (pageSize: number) => () => void;
}


function DxPagerPageSizeView({viewModel, selectPageSize}: IDxPagerPageSizeViewProps) {
  return (
    <div className="dx-pager-page-size">
      {
        viewModel.items.map((item) =>
          item.template({item, selectPageSize}))
      }
    </div>
  );
}

export type {IDxPagerPageSizeViewProps};
export {DxPagerPageSizeView};

// libs/angular-workspace/projects/angular-lib/components/pager/views/dx-pager-page-size-view.component.ts
import {ChangeDetectionStrategy, Component} from '@angular/core';
import {DxViewContracts} from '@dx/angular-common';
import {PageSizeAngularVM} from '../types';

interface DxPagerPageSizeActions {
  selectPageSize: (pageSize: number) => void;
}

@Component({
  template: '',
})
export abstract class DxPagerPageSizeViewContracts
  extends DxViewContracts<PageSizeAngularVM, DxPagerPageSizeActions> {
}

@Component({
  selector: 'dx-pager-page-size-view',
  template: `
    <div class="dx-pager-page-size">
      <dx-dynamic-template *ngFor="let item of viewModel.items"
                           [template]="item.template"
                           [data]="{
                           viewModel: item,
                           actions: { selectPageSize: actions.selectPageSize }
                           }">
      </dx-dynamic-template>
    </div>
  `,
  styleUrls: ['./dx-pager-page-size-view.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DxPagerPageSizeViewComponent extends DxPagerPageSizeViewContracts {
}
