// libs/angular-workspace/projects/angular-lib/components/simple-grid/dx-simple-grid.component.ts
import {Component, Input, OnChanges} from '@angular/core';
import {TAngularInputs} from '@dx/angular-common';
import {DxSimpleGridLogic, SimpleGridState} from '@dx/core/components/simpleGrid';
import {getDefaultSimpleGridInputs, ISimpleGridInputs} from '@dx/core/types/simpleGrid';

@Component({
  selector: 'dx-simple-grid',
  template: `
    <dx-simple-grid-table-container></dx-simple-grid-table-container>
    <ng-content></ng-content>
  `,
  styles: [':host { display: block }'],
  providers: [
    { provide: SimpleGridState, useClass: SimpleGridState },
    {
      provide: DxSimpleGridLogic,
      useFactory: (state: SimpleGridState<unknown>) => new DxSimpleGridLogic(state),
      deps: [SimpleGridState],
    },
  ]
})
export class DxSimpleGridComponent<TData>
  implements
    TAngularInputs<ISimpleGridInputs<TData>>,
    OnChanges {

  @Input() data = getDefaultSimpleGridInputs<TData>().data;
  @Input() columns = getDefaultSimpleGridInputs<TData>().columns;

  constructor(private logic: DxSimpleGridLogic<TData>) { }

  ngOnChanges(): void {
    this.logic.updateStateFromPropsAction({
      data: this.data,
      columns: this.columns,
    });
  }
}

// libs/react/src/components/simpleGrid/dxSimpleGrid.tsx
import React, {useEffect, useMemo} from 'react';
import {DxSimpleGridLogic, SimpleGridState} from '@dx/core/components/simpleGrid';
import {ISimpleGridInputs, getDefaultSimpleGridState} from '@dx/core/types/simpleGrid';
import {DxSimpleGridContext} from './dxSimpleGridContext';
import {DxSimpleGridTableContainer} from './containers/dxSimpleGridTableContainer';

interface IDxSimpleGridProps<TData>
  extends ISimpleGridInputs<TData> {
  children: React.ReactNode
}

function DxSimpleGrid<TData>(props: IDxSimpleGridProps<TData>) {
  const state = useMemo(() => new SimpleGridState<TData>(getDefaultSimpleGridState()), []);
  const logic = useMemo(() => new DxSimpleGridLogic(state), []);

  useEffect(() => logic.updateStateFromPropsAction({
    data: props.data,
    columns: props.columns,
  }), [props]);

  return (
    <DxSimpleGridContext.Provider value={logic}>
      <DxSimpleGridTableContainer<TData> />
      <div>
        {props.children}
      </div>
    </DxSimpleGridContext.Provider>
  )
}

export {DxSimpleGrid}
