// libs/angular/src/components/slide-toggle/dx-slide-toggle.component.ts
import {ChangeDetectionStrategy, Component, EventEmitter, Input, OnInit, Output} from '@angular/core';
import {
  DEFAULT_SLIDE_TOGGLE_INPUTS,
  ISlideToggleInputs,
  ISlideToggleOutputs,
  ISlideToggleState,
  SlideToggleActionUpdateStateFromInputs,
  SlideToggleContractManager,
  SlideToggleStore
} from "dx-core";

type TAngularInputs<TInputs> = Partial<TInputs>;
type TAngularOutputs<TOutputs> = Record<keyof TOutputs, EventEmitter<TOutputs[keyof TOutputs]>>

@Component({
  selector: 'dx-slide-toggle',
  templateUrl: './dx-slide-toggle.component.html',
  styleUrls: ['./dx-slide-toggle.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    {
      provide: SlideToggleStore,
      useClass: SlideToggleStore,
    },
    {
      provide: SlideToggleContractManager,
      useFactory: (store: SlideToggleStore) => new SlideToggleContractManager(store),
      deps: [SlideToggleStore],
    }],
})
export class DxSlideToggleComponent
  implements
    TAngularInputs<ISlideToggleInputs>,
    TAngularOutputs<ISlideToggleOutputs>,
    OnInit {

  @Input() value: boolean = DEFAULT_SLIDE_TOGGLE_INPUTS.value;
  @Input() text: string = DEFAULT_SLIDE_TOGGLE_INPUTS.text;
  @Input() textPosition: 'left' | 'right' = DEFAULT_SLIDE_TOGGLE_INPUTS.textPosition;

  @Output() valueChanged = new EventEmitter<boolean>;

  constructor(private contractManager: SlideToggleContractManager) { }

  ngOnInit(): void {
    this.contractManager.mapStateChangeToOutputs({
      valueChanged: {
        selector: (state: ISlideToggleState) => state.model.value,
        callback: (value: boolean) => this.valueChanged.emit(value)
      },
    });
  }

  ngOnChanges(): void {
    this.contractManager.mapInputChangeToState(new SlideToggleActionUpdateStateFromInputs({
      value: this.value,
      text: this.text,
      textPosition: this.textPosition,
    }));
  }

  ngOnDestroy(): void {
    this.contractManager.destroy();
  }
}

<div *ngIf="viewModel$ | async as viewModel"
     class="dx-slide-toggle"
     [class.-left]="viewModel.textPosition === 'left'"
     [class.-right]="viewModel.textPosition === 'right'"
     (click)="updateValue(!viewModel.value)">
  <dx-slide-toggle-indicator class="dx-slide-toggle__indicator"
                             [class.-left]="viewModel.textPosition === 'right'"
                             [class.-right]="viewModel.textPosition === 'left'"
                             [value]="viewModel.value">
  </dx-slide-toggle-indicator>
  <dx-slide-toggle-text [text]="viewModel.text"></dx-slide-toggle-text>
</div>

// libs/react/src/components/slideToggle/dxSlideToggle.tsx
import {
  DEFAULT_SLIDE_TOGGLE_INPUTS,
  ISlideToggleInputs,
  ISlideToggleOutputs,
  SlideToggleActionUpdateStateFromInputs,
  SlideToggleContractManager,
  SlideToggleStore
} from "dx-core";
import {DxSlideToggleContext} from "./dxSlideToggleContext";
import React, {useEffect, useMemo} from "react";
import {DxSlideToggleContainer} from "./containers/dxSlideToggleContainer";

type TReactInputs<TInputs> = TInputs;
type TReactOutputs<TOutputs> = Partial<Record<keyof TOutputs, (value: TOutputs[keyof TOutputs]) => void>>;

interface IDxSlideToggleProps extends
  TReactInputs<ISlideToggleInputs>,
  TReactOutputs<ISlideToggleOutputs> {}


function DxSlideToggle(props: IDxSlideToggleProps) {
  const store = useMemo(() => new SlideToggleStore(), []);
  const contractManager = useMemo(() => new SlideToggleContractManager(store), []);

  // init
  useEffect(() => {
    contractManager.mapStateChangeToOutputs({
      valueChanged: {
        selector: (state) => state.model.value,
        callback: (value: boolean) => props.valueChanged ? props.valueChanged(value) : undefined,
      }
    })

    // destroy
    return () => {
      contractManager.destroy();
    };
  }, []);

  // props changes
  useEffect(() => {
    contractManager.mapInputChangeToState(new SlideToggleActionUpdateStateFromInputs({
      value: props.value,
      text: props.text,
      textPosition: props.textPosition,
    }))
  }, [props]);

  return (
    <DxSlideToggleContext.Provider value={store} >
      <DxSlideToggleContainer />
    </DxSlideToggleContext.Provider>
  )
}

DxSlideToggle.defaultProps = DEFAULT_SLIDE_TOGGLE_INPUTS;

export {
  IDxSlideToggleProps,
  DxSlideToggle,
}
