// libs/angular-workspace/projects/angular-lib/components/simple-grid/containers/dx-simple-grid-table-container/dx-simple-grid-table-container.component.ts
import {ChangeDetectionStrategy, Component} from '@angular/core';
import {DxSimpleGridLogic} from '@dx/core/components/simpleGrid';
import {castUnknownToTemplate} from '@dx/angular-common';

@Component({
  selector: 'dx-simple-grid-table-container',
  templateUrl: './dx-simple-grid-table-container.component.html',
  styleUrls: ['./dx-simple-grid-table-container.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DxSimpleGridTableContainerComponent<TData> {
  headerVM$ = this.logic.headerVM$;
  rowsVM$ = this.logic.rowsVM$;

  utils = {
    castToTemplate: castUnknownToTemplate,
  }

  constructor(private logic: DxSimpleGridLogic<TData>) {
  }
}

<div class="dx-simple-grid-table">
  <div *ngIf="headerVM$ | async as headerVM"
       class="dx-simple-grid-table__header">
    <dx-simple-grid-header-cell
      *ngFor="let cell of headerVM.cells"
      [label]="cell.label"
      [template]="utils.castToTemplate(cell.template)">
    </dx-simple-grid-header-cell>
  </div>
  <div *ngIf="rowsVM$ | async as rowsVM"
    class="dx-simple-grid-table__body">
    <dx-simple-grid-row-container
     *ngFor="let row of rowsVM.data"
    [rowRecordId]="row.recordId"
    [data]="row.data"
    [cellData]="rowsVM.cellsData">
    </dx-simple-grid-row-container>
  </div>
</div>

// libs/react/src/components/simpleGrid/containers/dxSimpleGridTableContainer.tsx
import {DxSimpleGridLogic} from '@dx/core/components/simpleGrid';
import React from 'react';
import {useReactContext, useViewModel} from '../../../common/hooks';
import {DxSimpleGridContext} from '../dxSimpleGridContext';
import {DxSimpleGridRowContainer} from './dxSimpleGridRowContainer';
import {DxSimpleGridHeaderCell} from './dxSimpleGridHeaderCell';

import './dxSimpleGridTableContainer.scss';

function DxSimpleGridTableContainer<TData>() {
  const logic = useReactContext(DxSimpleGridContext) as DxSimpleGridLogic<TData>;

  const headerVM = useViewModel(logic.headerVM$);
  const rowsVM = useViewModel(logic.rowsVM$);

  return (
    <div className="dx-simple-grid-table">
      <div className="dx-simple-grid-table__header">
        {
          headerVM && headerVM.cells.map(({recordId, label, template}) => {
            const headerCellTemplate = template as THeaderCellTemplate;
            return <DxSimpleGridHeaderCell key={recordId} label={label} template={headerCellTemplate}/>
          })
        }
      </div>
      <div className="dx-simple-grid-table__body">
        {
          rowsVM && rowsVM.data.map((row) => {
            return <DxSimpleGridRowContainer
              key={row.recordId}
              rowRecordId={row.recordId}
              data={row.data}
              cellData={rowsVM.cellsData}/>
          })
        }
      </div>
    </div>
  )
}

export {DxSimpleGridTableContainer}
