// libs/angular-workspace/projects/angular-lib/components/simple-grid/containers/dx-simple-grid-row-container/dx-simple-grid-row-container.component.ts
import {ChangeDetectionStrategy, Component, Input, OnInit} from '@angular/core';
import {ISimpleGridTableRowsVMDataBaseCell} from '@dx/core/components/simpleGrid';
import {ESimpleGridColumnTypes} from '@dx/core/types/simpleGrid';
import {castUnknownToTemplate} from '@dx/angular-common';
import {asDataGetter, asDataKey} from '../../utils/dataCellTypeCast';

@Component({
  selector: 'dx-simple-grid-row-container',
  templateUrl: './dx-simple-grid-row-container.component.html',
  styleUrls: ['./dx-simple-grid-row-container.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DxSimpleGridRowContainerComponent<TData> implements OnInit {
  @Input() data?: TData
  @Input() cellData: ISimpleGridTableRowsVMDataBaseCell[] = [];
  @Input() rowRecordId: string = '';

  types = {
    cellType: ESimpleGridColumnTypes,
  };

  utils = {
    asDataGetter: asDataGetter,
    asDataKey: asDataKey,
    castToTemplate: castUnknownToTemplate,
  };

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="dx-simple-grid-row">
  <ng-container *ngFor="let cell of cellData">
    <ng-container [ngSwitch]="cell.type">
      <!-- data getter -->
      <ng-container *ngSwitchCase="types.cellType.getter">
        <dx-simple-grid-data-getter-cell
          *ngIf="utils.asDataGetter(cell) as dataGetterCell"
          [data]="data"
          [valueGetter]="dataGetterCell.valueGetter"
          [template]="utils.castToTemplate(dataGetterCell.template)">
        </dx-simple-grid-data-getter-cell>
      </ng-container>
      <!-- data key -->
      <ng-container *ngSwitchDefault>
        <dx-simple-grid-data-key-cell
          *ngIf="utils.asDataKey(cell) as dataKeyCell"
          [data]="data"
          [keyName]="dataKeyCell.keyName"
          [template]="utils.castToTemplate(dataKeyCell.template)">
        </dx-simple-grid-data-key-cell>
      </ng-container>
    </ng-container>
  </ng-container>
</div>

// libs/react/src/components/simpleGrid/containers/dxSimpleGridRowContainer.tsx
import {
  ISimpleGridTableRowsVMDataBaseCell,
  ISimpleGridTableRowsVMDataGetterCell,
  ISimpleGridTableRowsVMDataKeyCell
} from '@dx/core/components/simpleGrid';
import React from 'react';
import {ESimpleGridColumnTypes} from '@dx/core/types/simpleGrid';

import {DxSimpleGridDataKeyCell} from './dxSimpleGridDataKeyCell';
import {DxSimpleGridDataGetterCell} from './dxSimpleGridDataGetterCell';

import './dxSimpleGridRowContainer.scss';

interface IDxSimpleGridRowProps<TData> {
  data: TData;
  cellData: ISimpleGridTableRowsVMDataBaseCell[];
  rowRecordId: string;
}

function DxSimpleGridRowContainer<TData>(props: IDxSimpleGridRowProps<TData>) {
  return (
    <div className="dx-simple-grid-row">
      {
        props.cellData
          .map((cell) => {
            switch (cell.type) {
              case ESimpleGridColumnTypes.getter:
                const dataGetterCell = cell as ISimpleGridTableRowsVMDataGetterCell<TData>;
                const dataGetterCellTemplate = dataGetterCell.template as TDataGetterCellTemplate<unknown>;
                return <DxSimpleGridDataGetterCell
                  key={`${props.rowRecordId}-${dataGetterCell.recordId}`}
                  data={props.data}
                  valueGetter={dataGetterCell.valueGetter}
                  template={dataGetterCellTemplate}/>
              default:
                const dataKeyCell = cell as ISimpleGridTableRowsVMDataKeyCell<TData>;
                const dataKeyCellTemplate = dataKeyCell.template as TDataKeyCellTemplate<TData, keyof TData>;
                return <DxSimpleGridDataKeyCell
                  key={`${props.rowRecordId}-${dataKeyCell.recordId}`}
                  data={props.data}
                  keyName={dataKeyCell.keyName}
                  template={dataKeyCellTemplate}/>
            }
          })
      }
    </div>
  )
}

export {
  DxSimpleGridRowContainer
}
