// libs/angular-workspace/projects/angular-lib/components/slide-toggle/views/slide-toggle-text-view/dx-slide-toggle-text-view.component.ts
import {ChangeDetectionStrategy, Component, Input} from '@angular/core';
import {
  ISlideToggleTextVM
} from "@dx/core/components/slideToggle";

@Component({
  selector: 'dx-slide-toggle-text-view',
  templateUrl: './dx-slide-toggle-text-view.component.html',
  styleUrls: ['./dx-slide-toggle-text-view.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DxSlideToggleTextViewComponent {
  @Input() viewModel: ISlideToggleTextVM = {
    text: '',
  };
}

<div>
  {{ viewModel.text }}
</div>

// libs/react/src/components/slideToggle/views/dxSlideToggleTextView.tsx
import React from "react";
import {ISlideToggleTextVM} from "@dx/core/components/slideToggle";

interface IDxSlideToggleTextViewProps {
  viewModel: ISlideToggleTextVM,
}

const DEFAULT_DX_SLIDE_TOGGLE_TEXT_VIEW_PROPS: IDxSlideToggleTextViewProps = {
  viewModel: {
    text: '',
  }
}

function DxSlideToggleTextView({viewModel}: {viewModel: ISlideToggleTextVM}) {
  return (
    <div>
      {viewModel.text}
    </div>
  )
}

DxSlideToggleTextView.defaultProps = DEFAULT_DX_SLIDE_TOGGLE_TEXT_VIEW_PROPS;

export {DxSlideToggleTextView};
