// libs/react/src/components/slideToggle/views/dxSlideToggleIndicatorView.tsx
import React from "react";
import {ISlideToggleIndicatorVM} from "@dx/core/components/slideToggle";


import "./dxSlideToggleIndicatorView.scss";

interface IDxSLideToggleIndicatorViewProps {
  viewModel: ISlideToggleIndicatorVM,
}

const DEFAULT_DX_SLIDE_TOGGLE_INDICATOR_PROPS: IDxSLideToggleIndicatorViewProps = {
  viewModel: {
    value: false,
    textPosition: 'right'
  }
}

function DxSlideToggleIndicatorView({viewModel}: {viewModel: ISlideToggleIndicatorVM}) {
  return (
    <div className={`dx-slide-toggle-indicator ${viewModel.textPosition === 'right' ? '-left' : '-right'}`}>
      <div className={`dx-slide-toggle-line ${!viewModel.value ? '-off' : '-on'}`}>
        <div className={`dx-slide-toggle-thumb ${!viewModel.value ? '-off' : '-on'}`}>
        </div>
      </div>
    </div>
  )
}

DxSlideToggleIndicatorView.defaultProps = DEFAULT_DX_SLIDE_TOGGLE_INDICATOR_PROPS;

export {DxSlideToggleIndicatorView}

// libs/angular-workspace/projects/angular-lib/components/slide-toggle/views/slide-toggle-indicator-view/dx-slide-toggle-indicator-view.component.ts
import {ChangeDetectionStrategy, Component, Input} from '@angular/core';
import {
  ISlideToggleIndicatorVM
} from '@dx/core/components/slideToggle';

@Component({
  selector: 'dx-slide-toggle-indicator-view',
  templateUrl: './dx-slide-toggle-indicator-view.component.html',
  styleUrls: ['./dx-slide-toggle-indicator-view.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DxSlideToggleIndicatorViewComponent {
  @Input() viewModel: ISlideToggleIndicatorVM = {
    value: false,
    textPosition: 'right',
  };
}
