// libs/angular/src/components/slide-toggle/containers/dx-slide-toggle-indicator-container/dx-slide-toggle-indicator-container.component.ts
import {ChangeDetectionStrategy, Component} from '@angular/core';
import {
  getSlideToggleIndicatorVM,
  ISlideToggleIndicatorVM,
  SlideToggleStore
} from "dx-core";
import {Observable} from "rxjs";

@Component({
  selector: 'dx-slide-toggle-indicator-container',
  templateUrl: './dx-slide-toggle-indicator-container.component.html',
  styleUrls: ['./dx-slide-toggle-indicator-container.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DxSlideToggleIndicatorContainerComponent {

  viewModel$: Observable<ISlideToggleIndicatorVM> = this.store.getViewModel(
    (state) => ({
        value: state.model.value,
        textPosition: state.viewData.textPosition,
      }),
    getSlideToggleIndicatorVM,
  );

  constructor(private store: SlideToggleStore) {
  }
}

<dx-slide-toggle-indicator-view
  *ngIf="viewModel$ | async as viewModel"
  [viewModel]="viewModel">
</dx-slide-toggle-indicator-view>

// libs/react/src/components/slideToggle/containers/dxSlideToggleIndicatorContainer.tsx
import React, {useEffect, useState} from "react";
import {DxSlideToggleContext} from "../dxSlideToggleContext";
import {getSlideToggleIndicatorVM, ISlideToggleIndicatorVM, SlideToggleStore} from "dx-core";
import {DxSlideToggleIndicatorView} from "../views/dxSlideToggleIndicatorView";
import {getContext} from "../../../utils";


function DxSlideToggleIndicatorContainer() {
  const store = getContext<SlideToggleStore>(DxSlideToggleContext);
  const [viewModel, setViewModel] = useState<ISlideToggleIndicatorVM>();

  // init
  useEffect(() => {
    const subscription = store.getViewModel(
      (state) => ({
        value: state.model.value,
        textPosition: state.viewData.textPosition,
      }),
      getSlideToggleIndicatorVM,
    ).subscribe(setViewModel);

    // destroy
    return () => {
      subscription.unsubscribe();
    }
  }, []);

  return <DxSlideToggleIndicatorView viewModel={viewModel} />
}

export {DxSlideToggleIndicatorContainer}
