// libs/angular/src/components/slide-toggle/containers/dx-slide-toggle-text-container/dx-slide-toggle-text-container.component.ts
import {ChangeDetectionStrategy, Component} from '@angular/core';
import {getSlideToggleTextVM, ISlideToggleTextVM, SlideToggleStore} from "dx-core";
import {Observable} from "rxjs";

@Component({
  selector: 'dx-slide-toggle-text-container',
  templateUrl: './dx-slide-toggle-text-container.component.html',
  styleUrls: ['./dx-slide-toggle-text-container.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DxSlideToggleTextContainerComponent {

  viewModel$: Observable<ISlideToggleTextVM> = this.store.getViewModel(
    (state) => state.viewData.text,
    getSlideToggleTextVM,
  );

  constructor(private store: SlideToggleStore) {
  }
}

// libs/react/src/components/slideToggle/containers/dxSlideToggleTextContainer.tsx
import {DxSlideToggleTextView} from "../views/dxSlideToggleTextView";
import React, {useEffect, useState} from "react";
import {getSlideToggleTextVM, ISlideToggleTextVM, SlideToggleStore} from "dx-core";
import {DxSlideToggleContext} from "../dxSlideToggleContext";
import {getContext} from "../../../utils";


function DxSlideToggleTextContainer() {
  const store = getContext<SlideToggleStore>(DxSlideToggleContext);
  const [viewModel, setViewModel] = useState<ISlideToggleTextVM>();

  // init
  useEffect(() => {
    const subscription = store.getViewModel(
      (state) => state.viewData.text,
      getSlideToggleTextVM,
    ).subscribe(setViewModel);

    // destroy
    return () => {
      subscription.unsubscribe();
    }
  }, []);

  return <DxSlideToggleTextView viewModel={viewModel} />
}

export {DxSlideToggleTextContainer}
