// libs/angular-workspace/projects/angular-lib/components/slide-toggle/containers/dx-slide-toggle-container.component.ts
import {ChangeDetectionStrategy, Component, Inject, OnInit} from '@angular/core';
import {ContainerSlideToggleCore, SlideToggleVM, UpdateValueAction} from '@dx/core/components/slideToggle';
import {useViewModel} from '@dx/angular-common';
import {Observable} from 'rxjs';
import {SLIDE_TOGGLE_CONTEXT_TOKEN, SlideToggleContext} from '../context';


@Component({
  selector: 'dx-slide-toggle-container',
  template: `
    <div *ngIf="viewModel$ | async as viewModel"
         class="dx-slide-toggle"
         [class.-left]="viewModel.dictionary.textPosition === 'left'"
         [class.-right]="viewModel.dictionary.textPosition === 'right'"
         (click)="updateValue()">
      <dx-dynamic-template [template]="viewModel.dictionary.indicatorView"
                           [data]="{viewModel}">
      </dx-dynamic-template>
      <dx-dynamic-template [template]="viewModel.dictionary.textView"
                           [data]="{viewModel}">
      </dx-dynamic-template>
    </div>
  `,
  styleUrls: ['./dx-slide-toggle-container.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DxSlideToggleContainerComponent implements OnInit {
  viewModel$?: Observable<SlideToggleVM>;

  private core?: ContainerSlideToggleCore;

  constructor(@Inject(SLIDE_TOGGLE_CONTEXT_TOKEN) private contextContainer: SlideToggleContext) {
  }

  ngOnInit(): void {
    this.core = this.contextContainer.context!;
    this.viewModel$ = useViewModel(this.core!.viewModels.general);
  }

  updateValue(): void {
    this.core?.dispatch(new UpdateValueAction());
  }
}

// libs/react/src/components/slideToggle/containers/dxSlideToggleContainer.tsx
import React, {useCallback, useContext} from 'react';
import {SlideToggleVM, UpdateValueAction} from '@dx/core/components/slideToggle';

import './dxSlideToggleContainer.scss';
import {useViewModel} from '../../../internal';
import {SlideToggleContext} from '../dxSlideToggleContext';
import {SlideToggleReactVM} from '../types';


const DxSlideToggleContainer = React.memo(() => {
  const core = useContext(SlideToggleContext)!;
  const {model, dictionary} = useViewModel<SlideToggleVM, SlideToggleReactVM>(core.viewModels.general);
  console.log('container: ', model);

  const updateValueCallback = useCallback(
    () => core.dispatch(new UpdateValueAction()),
    []);

  return (
    <div className={`dx-slide-toggle ${dictionary.textPosition === 'left' ? '-left' : '-right'}`}
         onClick={updateValueCallback}>
      {
        dictionary.indicatorView({
          data: {
            value: model.value,
            textPosition: dictionary.textPosition
          }
        })
      }
      {
        dictionary.textView({data: {text: dictionary.text}})
      }
    </div>
  );
});

export {DxSlideToggleContainer};
