// libs/react/src/components/slideToggle/containers/dxSlideToggleContainer.tsx
import React, {useCallback, useEffect, useState} from "react";
import {getRootContainerVM, IRootContainerVM, SlideToggleActionUpdateValue, SlideToggleStore} from "dx-core";
import {DxSlideToggleContext} from '../dxSlideToggleContext';
import {DxSlideToggleIndicatorContainer} from "./dxSlideToggleIndicatorContainer";
import {DxSlideToggleTextContainer} from "./dxSlideToggleTextContainer";
import {getContext} from "../../../utils";


import "./dxSlideToggleContainer.scss";

function DxSlideToggleContainer() {
  const store = getContext<SlideToggleStore>(DxSlideToggleContext);
  const [viewModel, setViewModel] = useState<IRootContainerVM>();

  const updateValue = useCallback(() => {
    store.doAction(new SlideToggleActionUpdateValue(!viewModel?.value))
  }, [viewModel]);

  // init
  useEffect(() => {
    const subscribe = store.getViewModel(
      (state) => ({
        value: state.model.value,
        textPosition: state.viewData.textPosition,
      }),
      getRootContainerVM,
    ).subscribe(setViewModel);

    // destroy
    return () => {
      subscribe.unsubscribe();
    }
  }, []);

  return (
    <div className={`dx-slide-toggle ${viewModel?.textPosition === 'left' ? '-left' : '-right'}`}
         onClick={updateValue}>
      <DxSlideToggleIndicatorContainer />
      <DxSlideToggleTextContainer />
    </div>
  )
}

export {DxSlideToggleContainer};

// libs/angular/src/components/slide-toggle/containers/dx-slide-toggle-container/dx-slide-toggle-container.component.ts
import {ChangeDetectionStrategy, Component} from '@angular/core';
import {getRootContainerVM, IRootContainerVM, SlideToggleActionUpdateValue, SlideToggleStore} from "dx-core";
import {Observable} from "rxjs";

@Component({
  selector: 'dx-slide-toggle-container',
  templateUrl: './dx-slide-toggle-container.component.html',
  styleUrls: ['./dx-slide-toggle-container.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DxSlideToggleContainerComponent {

  viewModel$: Observable<IRootContainerVM> = this.store.getViewModel(
    (state) => ({
      value: state.model.value,
      textPosition: state.viewData.textPosition,
    }),
    getRootContainerVM,
  )

  constructor(private store: SlideToggleStore) { }

  updateValue(newValue: boolean): void {
    this.store.doAction(new SlideToggleActionUpdateValue(newValue));
  }
}

<div *ngIf="viewModel$ | async as viewModel"
    class="dx-slide-toggle"
    [class.-left]="viewModel.textPosition === 'left'"
    [class.-right]="viewModel.textPosition === 'right'"
     (click)="updateValue(!viewModel.value)">
  <dx-slide-toggle-indicator-container>
  </dx-slide-toggle-indicator-container>
  <dx-slide-toggle-text-container>
  </dx-slide-toggle-text-container>
</div>
