// libs/react/src/components/simpleButton/dxSimpleButton.tsx
import React, {useEffect, useMemo} from "react";
import {DxSimpleButtonLogic, SimpleButtonState} from '@dx/core/components/simpleButton';
import {useViewModel} from '../../common/hooks';
import {IDxSimpleButtonProps} from './dxSimpleButtonProps';

import './dxSimpleButton.scss';


function DxSimpleButton(props: IDxSimpleButtonProps) {
  const state = useMemo(() => new SimpleButtonState(), []);
  const logic = useMemo(() => new DxSimpleButtonLogic(state), []);

  const viewModel = useViewModel(logic.viewModel$);

  useEffect(() => {
    logic.updateStateFromProps(props);
  }, [props])

  return (
    <React.Fragment>
      {viewModel && <button className="dx-simple-button">{viewModel.text}</button>}
    </React.Fragment>
  )
}

export {
  DxSimpleButton,
}

// libs/angular-workspace/projects/angular-lib/components/simple-button/dx-simple-button.component.ts
import {ChangeDetectionStrategy, Component, Input, OnChanges} from '@angular/core';
import {DxSimpleButtonLogic, SimpleButtonState} from '@dx/core/components/simpleButton';
import {ISimpleButtonState, SIMPLE_BUTTON_DEFAULT_STATE} from '@dx/core/types/simpleButton';
import {TAngularInputs} from '@dx/angular-common';


@Component({
  selector: 'dx-simple-button',
  templateUrl: './dx-simple-button.component.html',
  styleUrls: ['./dx-simple-button.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    { provide: SimpleButtonState, useClass: SimpleButtonState },
    {
      provide: DxSimpleButtonLogic,
      useFactory: (state: SimpleButtonState) => new DxSimpleButtonLogic(state),
      deps: [SimpleButtonState],
    }
  ]
})
export class DxSimpleButtonComponent implements
  OnChanges,
  TAngularInputs<ISimpleButtonState> {

  @Input()
  text = SIMPLE_BUTTON_DEFAULT_STATE.text;

  viewModel$ = this.logic.viewModel$;

  constructor(private logic: DxSimpleButtonLogic) { }

  ngOnChanges(): void {
    this.logic.updateStateFromProps({
      text: this.text,
    });
  }
}

<button class="dx-simple-button">
  {{ (viewModel$ | async)?.text }}
</button>
